### ISSUE TITLE
`Id` shall be returned when an Insert is made

### ISSUE THREAD

**Issue by 0cv** [k-capehart/go-salesforce#42]
As the title says, we shall return the `Id` provided in the response from Salesforce so that this can be used in other operations, etc.

**Comment by k-capehart** [comment]
Hey @0cv , I love this suggestion. Were you thinking that this should be implemented for all Insert methods? i.e. `InsertOne`, `InsertCollection`, `InsertComposite`, `InsertBulk`?

Also, did you have any plans to submit a PR for this or should I take a look?

**Comment by 0cv** [comment]
@k-capehart yes a good PR would be to implement all these methods which could take a bit of time .. For now, I'm just evaluating various Go framework so feel free to implement that feature

**Comment by k-capehart** [comment]
@0cv This is merged in now. I'll create a release shortly.
