### ISSUE TITLE
300 error code should not be consider as error in doRequest function, get account by external id api returns 300

### ISSUE THREAD

**Issue by aishmuru** [k-capehart/go-salesforce#62]
Hi @k-capehart,

doRequest function in salesforce.go file is consider error for below condition:
        if resp.StatusCode < 200 || resp.StatusCode > 299 {
		resp, err = processSalesforceError(*resp, auth, payload)
	}

Whereas, get account by external id api is returning a list of multiple accounts and status code is 300 which should be supported in our case since multiple accounts associated to an external id is allowed.

For API reference: https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/using_resources_retrieve_with_externalid.htm
(FYI this is very limited usecase in documentation where it will return single object with success response instead of list with 300).

Is it possible to include 300 status code in success response?

thanks,
Aishmuru

**Comment by k-capehart** [comment]
Hello @aishmuru!

That's interesting. I'll test it out on my end when I get a chance but I don't see a problem with including `300` as an expected status code. Feel free to create a PR to fix this in the meantime.

**Comment by k-capehart** [comment]
Hello again @aishmuru,

I tested this out in my org and did not receive a 300. Salesforce returned a 200 instead. 

![image](https://github.com/user-attachments/assets/8a8ee2bc-24a6-43db-a915-8328f6b89580)

I looked into why this could be and found something interesting. From the [documentation](https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/errorcodes.htm#:~:text=%E2%80%9CNo%20Content%E2%80%9D%20success%20code%2C%20for%20DELETE%20requests,ID%20exists%20in%20more%20than%20one%20record.): `300 The value returned when an external ID exists in more than one record.`

As this is unexpected behavior, I would stand by go-salesforce seeing this as an error. ExternalIds should be unique. To resolve this, I would check for duplicates in your org.

**Comment by k-capehart** [comment]
I'm a little hesitant, because I think an `ExternalID` should ideally be unique. However, Salesforce doesn't require it to be, hence this edge case.

This is what Salesforce returns when there are multiple matches. This doesn't seem to be the most useful response, as all you get is the ID. I'm open to suggestions on how to handle this. I think the best path forward is to just return a slice of strings and let the user decide how to handle the response, otherwise we'd get too in the weeds.

![image](https://github.com/user-attachments/assets/a8bac04a-d0ed-47db-a3dc-51644d7b2cb9)

**Comment by aishmuru** [comment]
Hello @k-capehart 
I think we can send response as it is for 300 instead of considering it as error and let people decide how to handle it.
But do you think there will be any issue for other apis if they returns 300 response?

**Comment by k-capehart** [comment]
I don't think it should be a problem. I've been thinking about it, and really it should return "something" if there is a match, even if there are conflicting records.

**Comment by k-capehart** [comment]
@aishmuru I implemented the fix. It's available in v2.1.2.
