### ISSUE TITLE
[jwtFlow] domain test.salesforce.com

### ISSUE THREAD

**Issue by TuSKan** [k-capehart/go-salesforce#70]
Hi,

On jwtFlow,  when domain=https://test.salesforce.com, it changes to https://login.salesforce.com

On this part of jwtFlow function:
```go
if strings.Contains(audience, "sandbox") {
  audience = "https://test.salesforce.com"
} else {
  audience = "https://login.salesforce.com"
}
```

**Comment by k-capehart** [comment]
Ahh, good catch. I'll fix this now.

**Comment by k-capehart** [comment]
Ahh, ok this is supported in the JWT flow but not in the Client Credentials flow. Now I understand. Also in my testing, I was using a developer org and so actually needed to use `login.salesforce.com` instead of `test.salesforce.com` which was throwing me off 😆 

Thank you for explaining!
