### ISSUE TITLE
[question] github.com/mitchellh/mapstructure archived

### ISSUE THREAD

**Issue by TuSKan** [k-capehart/go-salesforce#72]
The package [mapstructure](github.com/mitchellh/mapstructure) has been archived by the owner on Jul 22, 2024. It is now read-only.

I think you be good to look for a alternative for mapstructure.

There is a maintenance fork here [github.com/go-viper/mapstructure/v2](github.com/go-viper/mapstructure/v2).

I will submit a PR to change that, all tests are passing fine.

**Comment by k-capehart** [comment]
Thanks for noticing this and fixing it!
